### ISSUE TITLE
Vue router conflicts with WordPress

### ISSUE THREAD

**Issue by dchenier** [coe-google-apps-support/oct-portal#14]
The <vue-router /> that comes with vue-clie uses a hash #  in url to define and move to different routs.  This seems to conflict with WordPress (or Divi).  

We should swap out the <router-view />in [AppIdeas](https://github.com/coe-google-apps-support/oct-portal/blob/master/ideas/ideas-wordpress-plugin/src/AppIdeas.vue) for something else. The Simple routing defined [here](https://vuejs.org/v2/guide/routing.html) should be work well.

**Comment by j-rewerts** [comment]
A potential solution can be found [here](https://router.vuejs.org/en/essentials/history-mode.html). This might make local dev a bit trickier though.

**Comment by j-rewerts** [comment]
This turned out to be pretty easy. We just have to make sure our servers support history-based fallback. For the webpack dev server, [this page](https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback) helps.
