### ISSUE TITLE
Add secondary form fields to new initiative form

### ISSUE THREAD

**Issue by dchenier** [coe-google-apps-support/oct-portal#23]
see document grom @g-nux

**Comment by dchenier** [comment]
[OCT Portal document from Gregory](https://drive.google.com/open?id=1ZCcyWiMpXLkwsUVT4NS0QUZiOveuyP9lZZz0mguXcSo)

[Mockup from Tonie](https://docs.google.com/document/d/1L9LqpcLq6OSnjAgVRAWvTeYaNYr5yDR2OTUggQ5nsVQ/edit)

[Mockup of Tonie with comments](https://drive.google.com/open?id=1VQHC0lrnLFSgMF_GlUltX-JnpbmrCvyR)

**Comment by j-rewerts** [comment]
Would it be okay to exclude department/branch for now? I think we should be able to pull that info from somewhere eventually. @g-nux Any insight?

**Comment by dchenier** [comment]
As discussed yesterday we will do exactly as @j-rewerts says, and pull it from AD or that people web service on our internal network

**Comment by j-rewerts** [comment]
This will mostly be undone by #54
