### ISSUE TITLE
Make the initiative listing look better

### ISSUE THREAD

**Issue by dchenier** [coe-google-apps-support/oct-portal#26]
@j-rewerts  suggested cards for the initiatives rather than a simple listing.

I think it's a great idea!

**Comment by j-rewerts** [comment]
I took the first step in prettying up the list [here](https://github.com/coe-google-apps-support/oct-portal/commit/1e7f17c221f2b4d895aa9292fc0142a1924b4a92). I've still got some more work to do before we can consider this issue resolved.

**Comment by j-rewerts** [comment]
For an idea of how it looks right now:
![image](https://user-images.githubusercontent.com/8295080/34920725-4341a53c-f934-11e7-96e7-1d59970050ef.png)

**Comment by j-rewerts** [comment]
Now it looks like: 
![image](https://user-images.githubusercontent.com/8295080/35130594-fd12fc20-fc7e-11e7-8d0c-1a978799fe5c.png)

**Comment by j-rewerts** [comment]
I'm leaving this open until I can get fade in animations for the cards, as well as using the single page view for opening and closing cards.

When you click VIEW, the card will expand to take up more space, as well as move out of the standard document flow.

**Comment by j-rewerts** [comment]
I'm going to try to replace the backgrounds of these cards with some city pics.

**Comment by j-rewerts** [comment]
![image](https://user-images.githubusercontent.com/8295080/35421818-81f6a602-0202-11e8-9a52-7d4c59fabf53.png)

**Comment by j-rewerts** [comment]
It's a little more responsive as well.
