### ISSUE TITLE
Tame the wild colors

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/oct-portal#46]
We need to DIVI theme and material design to be more seamless.

**Comment by j-rewerts** [comment]
This:
![image](https://user-images.githubusercontent.com/8295080/35403701-ccc39cb6-01bd-11e8-86ce-0765f07a5e30.png)

VS this:
![image](https://user-images.githubusercontent.com/8295080/35403722-e1e7b2c6-01bd-11e8-9cd2-ebb27517e702.png)

**Comment by dchenier** [comment]
I vote for the one with background colour FEFEFE rather than 009688!

**Comment by dylrob** [comment]
The white background may blend better with the white background of the divi theme.. make it look less like an embedded object within a WP site.

**Comment by j-rewerts** [comment]
Done.
93d8ffb

**Comment by j-rewerts** [comment]
I'll probably continue getting feedback on color stuff in this issue.

**Comment by j-rewerts** [comment]
This is the new initiative's style:
![image](https://user-images.githubusercontent.com/8295080/35421867-d0627c44-0202-11e8-8862-c22c10c10f40.png)

Too colorful?

**Comment by j-rewerts** [comment]
For now, I'll only use the teal. We can add more colors when Janice gets on board.

**Comment by j-rewerts** [comment]
![image](https://user-images.githubusercontent.com/8295080/35475337-dde8bbe6-0359-11e8-8a36-95438e1e467e.png)

**Comment by j-rewerts** [comment]
Closed (for now) by c5743a9
