### ISSUE TITLE
"Ideas_API" in Vue needs to come from configuration

### ISSUE THREAD

**Issue by dchenier** [coe-google-apps-support/oct-portal#61]
Our build server builds the Vue application in production mode, which "hard-codes" the IDEAS_API as defined by the [prod.env.js](https://github.com/coe-google-apps-support/oct-portal/blob/master/plugins/ideas/config/prod.env.js) file. 

We need to use the same build of the application on our dev server as well as the production server.  Currently the dev server now points the API to production.  We need to fix this somehow.

WordPress can pass in a setting through the [route](https://github.com/coe-google-apps-support/oct-portal/blob/902478dd0086f56527830895dca9079eedcd76cb/plugins/ideas/src/AppIdeas.vue#L17) setting, but this isn't being respected by the Vue app.

**Comment by j-rewerts** [comment]
When you say same build on dev as it is on prod, you mean we should expose some sort of environment variable, right? Instead of having separate prod and dev front ends, we just look for a node.env.IDEAS_API, which for prod points [here](https://octportal.edmonton.ca:5000/Ideas), but for dev may point [here](https://octportal.dev.edmonton.ca:5000/Ideas) (for example).

**Comment by dchenier** [comment]
You are right that we should not have separate prod and dev front ends, but how do we set environment variable at run-time?  This application isn't served by Node.js; rather it's served by WordPress (Apache), and run entirely in the browser.

**Comment by dchenier** [comment]
The 'initialize-ideas' event comes from [here](https://github.com/coe-google-apps-support/oct-portal/blob/902478dd0086f56527830895dca9079eedcd76cb/plugins/ideas/src/main.js#L31), which comes from the initialize() method being called by WordPress [here](https://github.com/coe-google-apps-support/oct-portal/blob/902478dd0086f56527830895dca9079eedcd76cb/plugins/ideas/php/coe-ideas.php#L126).  

The logic in WorkPress is a little complicated due to the fact that I considered we might have more than one Vue app on the page.  Anything hanging off of the javascript global window.coe would be a candidate for "initialization", which is why we have that weird logic at the end of [main.js](https://github.com/coe-google-apps-support/oct-portal/blob/master/plugins/ideas/src/main.js).

To answer your question about dev builds being pushed directly to prod, there's 2 reasons we can't rebuild:
1) Node and NPM aren't installed on the server (maybe we could install them), and 
2) It's only the 3 .js files that should get built into the WordPress plugins directory: app, manifest, and vendor (well, actually their .map files too).

So our build server has 2 main phases: Build and Release.  Build produces an artifact that the Release system should be able to use.  Release should be able to deploy the same artifact to all environments and just supply different configuration settings appropriate to their environments.  Not rebuilding is what enforces the consistency and reliability of our application.

**Comment by dchenier** [comment]
Now, having said all of this I suppose we can make an exception in this case.  Although the production servers don't have NPM and Node, during Release we can use an agent that does have it and build that one project then. Because Release has the same tasks available as Build, this is possible.

**Comment by dchenier** [comment]
looks like we need to modify the build process to take in a parameter to decide which environment we're building for; https://github.com/coe-google-apps-support/oct-portal/blob/55275a923ab0961537318f82da0971596e159caa/plugins/ideas/build/build.js#L12
